[package]
name = "jsoneditor"
version = "0.1.0"
authors = ["Nubzzin <matheus.thelas@hotmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
